package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, 22 May, 2023 4:13:33 PM IST
*/

public interface CalculatorOperations 
{
  double add (double num1, double num2);
  double subtract (double num1, double num2);
  double multiply (double num1, double num2);
  double divide (double num1, double num2);
} // interface CalculatorOperations
